### ISSUE TITLE
Order of LEDS in function leds.circle is reversed in playground compared to the physical Thymio.

### ISSUE THREAD

**Issue by riedo** [Mobsya/aseba#186]
Reported by a user on the forum: In playground, the arguments start with the front LED and turn counter-clockwise, on the real robot it is clockwise.
![image](https://user-images.githubusercontent.com/1862778/43268705-9c104696-90f1-11e8-8904-a0dff4ee4642.png)

**Comment by riedo** [comment]
actually the bug is in Enki I think

**Comment by mbonani** [comment]
fixed
