### ISSUE TITLE
Control the TDM from the launcher

### ISSUE THREAD

**Issue by cor3ntin** [Mobsya/aseba#205]

**Comment by mbonani** [comment]
it is not working on last buld

**Comment by mbonani** [comment]
probably it is the problem that it is not working if you install it in program files, should be fix for make it test to more people.

**Comment by cor3ntin** [comment]
Can they test in a user-owned directory for now?

**Comment by mbonani** [comment]
yes we can test, but if the doc for testing become to complicate tests will for sure fail and not for the righr reason

**Comment by mbonani** [comment]
sometime TDM is not closed with Launcher
