### ISSUE TITLE
Package the launcher in the windows installer

### ISSUE THREAD

**Issue by cor3ntin** [Mobsya/aseba#210]
The launcher needs to be properly packaged in the windows installer, including all the qml dependencies

**Comment by cor3ntin** [comment]
I'm attempting to make use of the QML compiler, it makes packaging and deployment much easier while at the same time allowing compile faster times.
I had to upgrade Qt to 5.11 on most platforms but Linux though

**Comment by mbonani** [comment]
could we still install driver?

**Comment by cor3ntin** [comment]
@mbonani this is unrelated to the drivers - the driven still can and must be installed, nothing changed !

**Comment by cor3ntin** [comment]
Done.
This is very much targeted towards Alpha 1, but a lot of works remain to make the launcher ready for release.
