### ISSUE TITLE
Aseba Studio : Width of values column too big

### ISSUE THREAD

**Issue by dburnier** [Mobsya/aseba#230]
Why the width of Values column for the variables is so big by default ?

That's really boring to have to systematically resize this column width when we want to modify values when the window of AsebaStudio does not occupy all the screen; otherwise the values can be well modified but the column name disappears partially or totally.

I suggest to size the width in order to can display the "maximum" value -32768.

Was already submited on aseba-community (see #295 for the discussion) and still an issue on Aseba Studio version 1.6.0
<img width="292" alt="capture" src="https://user-images.githubusercontent.com/2941625/45541132-782bf600-b80e-11e8-8c3b-098128fe9ec0.PNG">

**Comment by cor3ntin** [comment]
This is fixed in the master and will ship with the next version of Aseba.
Please note that the master branch is at the moment not usable in production.
