### ISSUE TITLE
Aseba Studio 1.6.0 : Local event deleted from local event list

### ISSUE THREAD

**Issue by hellgheast** [Mobsya/aseba#262]
When an local event is drag & dropped to the global event list, it seems that it is deleted from the local event local.
In the additionnal screenshots i drag & dropped the button.backward event.
**Before drag and drop to global events**
<img width="555" alt="beforemanip" src="https://user-images.githubusercontent.com/4338715/46172163-09857880-c2a3-11e8-9d0d-e5cc73a3b160.PNG">
**After drag and drop to global events**
<img width="560" alt="aftermanip" src="https://user-images.githubusercontent.com/4338715/46172162-08ece200-c2a3-11e8-8c2c-5948a38e5375.PNG">

**Comment by mbonani** [comment]
Hello,
Normally you should only drag to the code zone in the center and not to the global events. 
I got also this bug on version 1.6 that was compile with QT4.8.
With latest compilation it is no more present using Qt5. 
So when we have new version 1.7 it should be corrected.
Regards
