### ISSUE TITLE
in macosx Thymio webbridge (aseba 1.6.1) process is still here even we close the terminal 

### ISSUE THREAD

**Issue by mbonani** [Mobsya/aseba#285]
also not on all mac the terminal appear and it is not listed in the "force close application" it is only visible in the process monitor

**Comment by mbonani** [comment]
after more test, the process is kill normally closing the terminal when there is no robot connected, but when one thymio is connect the closing do not kill the process. A ctr-c kill the process in the terminal

**Comment by cor3ntin** [comment]
Fixed
