### ISSUE TITLE
Message in the firmware updater

### ISSUE THREAD

**Issue by FrancescoMondada** [Mobsya/aseba#299]
Comment from a user:
"en flashant le Thymio avec le logiciel prévu, j’ai lu les consignes de non-débranchement habituelles. A la fin du processus, seule la barre de progression verte à 100% indique la fin. J’ai hésité à retirer le câble. Après quelques instants, j’ai quand même retiré l’USB. Un petit dialogue indiquant la fin du processus clarifierait la situation. "

**Comment by cor3ntin** [comment]
We are moving the firmware update feature in the launcher - the new UI doesn't have this issue
