### ISSUE TITLE
graphs in new studio should have time window or at least a manual refresh button (workaround until a graph suite is released in 2.0.1)

### ISSUE THREAD

**Issue by mbonani** [Mobsya/aseba#379]
as previously an option can be chosen given also the time choice (default 10sec)

**Comment by mbonani** [comment]
at least a refresh button

**Comment by KunjanChauhan** [comment]
Status agreed at 2020 02 17 meeting: 

- [ ] 1. Davide and Valentine to discuss re-positioning of button to a more user friendly location
- [ ] 2. Davide will place into pull req
- [ ] 3. Michael to test

**Comment by mbonani** [comment]
the actual position on top is ok for me, I think we can go foward on this, or @ValentinaTibs do you think it should be like before at bottom?

**Comment by mbonani** [comment]
fix in c6abf298ae9751aefae138b5538e733280f3d8e1
