### ISSUE TITLE
programming a thymio in VPL clears other tab

### ISSUE THREAD

**Issue by ogoletti** [Mobsya/aseba#382]
when two thymio are connected to the same network and you try to program one of them with the VPL editor, the other tab is cleared.

**Comment by cor3ntin** [comment]
VPL really isn't designed to support networks.
In a future version, we will prohibit launching using VPL on multi-nodes networks

**Comment by cor3ntin** [comment]
> we will prohibit launching using VPL on multi-nodes networks
Done
