### ISSUE TITLE
Mistake in blockly code for friendly behaviour

### ISSUE THREAD

**Issue by ogoletti** [Mobsya/aseba#383]
Hello, there is a mistake in the blockly code given here : https://aseba.wdfiles.com/local--files/en:thymiobehaviourfriendly/amicalV3-blockly.aesl
a max=0 is missing in the get_max_and_speed_diff procedure.

**Comment by mbonani** [comment]
on which page of Thymio site you find the code?

**Comment by ogoletti** [comment]
https://www.thymio.org/fr:thymiobehaviourfriendly

**Comment by mbonani** [comment]
it is corrected thanks,
you are also welcome to edit yourself if you found something wrong and you have the solution.
regards
