### ISSUE TITLE
closing Launcher may crash studio

### ISSUE THREAD

**Issue by mbonani** [Mobsya/aseba#404]
When you have a studio running , if you close Launcher it makes crash studio. It is specially doing that when you make it a second time. 
First time you close studio is working showing that robots are unconnected you relaunch and robot connects again. Closing launcher second time crashes studio.

**Comment by cor3ntin** [comment]
crap...

**Comment by cor3ntin** [comment]
Ok - on linux - maybe windows specific ?

**Comment by cor3ntin** [comment]
@cbarraud did you repro this one ?

**Comment by mbonani** [comment]
still there, not systematic but it happen after 2-3 trials

 Exception non gérée à 0x00007FFA9D3C14EE (Qt5Core.dll) dans asebastudio.exe : 0xC0000005 : Violation d'accès lors de la lecture de l'emplacement 0xFFFFFFFFFFFFFFFF.
![image](https://user-images.githubusercontent.com/1000934/54120172-58f5d600-43f7-11e9-8f89-76572590010f.png)

**Comment by cor3ntin** [comment]
What is the reproduction method exactly ?

Le lun. 11 mars 2019 à 12:16, Michael Bonani <notifications@github.com> a
écrit :

**Comment by mbonani** [comment]
open launcher and studio
close only the launcher and open it again until it make crach studio on a close of the launcher
