### ISSUE TITLE
blockly load and save is not working

### ISSUE THREAD

**Issue by mbonani** [Mobsya/aseba#409]
probably link to last improvment of TDM, was working before

**Comment by cor3ntin** [comment]
I fixed an issue in blockly but... Making saving works with the Qt view thing will take me a bit more time

**Comment by cor3ntin** [comment]
Fixed in  #425

**Comment by mbonani** [comment]
saving work but openning is not working here attached a aesl generated by latest build
[test-save-blockly.zip](https://github.com/Mobsya/aseba/files/3723370/test-save-blockly.zip)

**Comment by cor3ntin** [comment]
Fixed here https://github.com/Mobsya/thymio-blockly-standalone/commit/7f515b66a5c28df33ed2d5abc8fc423ea894d56c
