### ISSUE TITLE
aseba studio text zooming is strange with police changing

### ISSUE THREAD

**Issue by mbonani** [Mobsya/aseba#411]
![image 2](https://user-images.githubusercontent.com/1000934/53046550-98807080-3490-11e9-96e5-f3f718eb13a0.png)

**Comment by cor3ntin** [comment]
I don't have the issue on either of 2 my computers :(

**Comment by cor3ntin** [comment]
@cbarraud can, you repro ?

**Comment by cor3ntin** [comment]
Only windows 8 ?

**Comment by mbonani** [comment]
not seen in win 10

**Comment by mbonani** [comment]
seems to be ok now
