### ISSUE TITLE
Thymio VPL error icons too small

### ISSUE THREAD

**Issue by cbarraud** [Mobsya/aseba#412]
![image](https://user-images.githubusercontent.com/4930020/53083704-b33dfe00-34ff-11e9-9899-9080fad3b4e8.png)

The icon with the ! should be bigger than that.

I am using the 1.6.9 beta that is on Basecamp for the tests. Windows 8.1. Firmware 13 on the robot.

**Comment by cor3ntin** [comment]
I thought this one would be simple... boy was I wrong

**Comment by mbonani** [comment]
is that the only icons that are too smal? (because png instead of svg?) @cor3ntin can you make a screen shot of icon on hires screen, or have a list of them that have to be transform for @Vincebecker

**Comment by cor3ntin** [comment]
nope,  these are svgs - it's more complicated than that
