### ISSUE TITLE
Detect new  firmware versions

### ISSUE THREAD

**Issue by mbonani** [Mobsya/aseba#415]

**Comment by cor3ntin** [comment]
I'm not sure I remember which firmware 12 is.
Re-Connection (as in "oh, I know this device") absolutely needs the UUID

**Comment by mbonani** [comment]
12 is without UUID, 
So perhaps we should: improve the upgrade facilities or good communicate on it.

**Comment by cor3ntin** [comment]
Sure, that is planned for later, in the meantime I think we can hardcode a message in the launcher

**Comment by mbonani** [comment]
simple test if <13 show upgrade message

**Comment by cor3ntin** [comment]
#438

- Added simple icon + tooltip to notify user of tooltip
- The TDM will check update when plugging a device
- The TDM now therefore has the machinery to do https - which is what took the most time
- Device with fw or older are hardcoded to have an update
