### ISSUE TITLE
Possible to zoom the border of Scratch interface?

### ISSUE THREAD

**Issue by cbarraud** [Mobsya/aseba#468]
I was wondering if there was a way to zoom in the border of the Scratch interface and not just the "coding area". Here is what I have when I start it:

![image](https://user-images.githubusercontent.com/4930020/55141050-ce70de80-5139-11e9-96a7-a5e33ed269f1.png)

And this is what I have when I zoom the "coding area":

![image](https://user-images.githubusercontent.com/4930020/55141073-d92b7380-5139-11e9-95fb-ba4d2a46a19b.png)

But I couldn't find a way to zoom the border region. The text in the side blocks can be quite small there.

**Comment by cor3ntin** [comment]
@cbarraud i think you might have better luck asking that upstream https://github.com/llk/scratch-gui
It will be difficult for us to make modification to the scratch engine and the more we do the less we will be able to adopt new scratch versions

**Comment by mbonani** [comment]
![image](https://user-images.githubusercontent.com/1000934/55166267-18c08280-516f-11e9-93b0-156f1f7ec76d.png)
dans scratch3 online s ctr+roulette sur la barre bleu fait le zoom sur tout la page... est-ce que c'est pas qulque chose à activé dans Chromium?

**Comment by cor3ntin** [comment]
@mbonani that we probably can do indeed

**Comment by mbonani** [comment]
seems to work
