### ISSUE TITLE
Flatpak is missing libdashel.so.1

### ISSUE THREAD

**Issue by THS-on** [Mobsya/aseba#478]
I've build the current master and if I try to start Aseba Studio I get the following message:
```
Searching for  "asebastudio"
"asebastudio" found:  "/app/bin/asebastudio"
/app/bin/asebastudio: error while loading shared libraries: libdashel.so.1: cannot open shared object file: No such file or directory
```
I have a working Flatpak with libdashel build on 51ba1f23e033d6654741028b12254c700fb03d79 but unfortunately I cannot find what is different between my two setups is.

**Comment by cor3ntin** [comment]
I've changed the build a while ago not to link everything statically - and that introduced a regression
It should be fixed now.
