### ISSUE TITLE
Uniformise names Thymio Suite 2.0

### ISSUE THREAD

**Issue by cbarraud** [Mobsya/aseba#496]
In some part of the app, the names are not consistent. We should have "Thymio Suite 2.0" or "Thymio Suite" everywhere.

Names of the packages to download should be "Thymio-suite-2-0"
![image](https://user-images.githubusercontent.com/4930020/56040075-ea79a000-5d35-11e9-955a-dc9e1d74db38.png)

The window of Thymio-Launcher should be called "Thymio Suite"
![image](https://user-images.githubusercontent.com/4930020/56040143-0aa95f00-5d36-11e9-9f61-97190e8ee560.png)

The name of the app in the repository of the OS should be "Thymio Suite"
![launcher](https://user-images.githubusercontent.com/4930020/56040288-5a882600-5d36-11e9-96ed-5160452c0bcc.png)

In the installer, we should have "Thymio Suite 2.0" (everywhere in the wizard)
![image](https://user-images.githubusercontent.com/4930020/56040382-928f6900-5d36-11e9-929c-3079fb384bff.png)

**Comment by cbarraud** [comment]
I found here that the name of the app is still "Thymio launcher.exe"
![image](https://user-images.githubusercontent.com/4930020/56208936-a0a0fa80-6052-11e9-95ad-ba3f3a17ae04.png)

Here is the version (just downloaded now)
![image](https://user-images.githubusercontent.com/4930020/56208956-b2829d80-6052-11e9-9fc8-a06c8e2bc654.png)

I have to search for Thymio launcher then instead of Thymio Suite.
![image](https://user-images.githubusercontent.com/4930020/56209139-15743480-6053-11e9-82d8-3f731af7829e.png)


I tested on Windows 8.1.

**Comment by mbonani** [comment]
please try to uninstall first your old version
