### ISSUE TITLE
Blockly connection lost window still refers to Web bridge

### ISSUE THREAD

**Issue by cbarraud** [Mobsya/aseba#504]
![image](https://user-images.githubusercontent.com/4930020/56279437-64c86c80-6108-11e9-8215-185fbc1ffb96.png)
We should have something like "Thymio is disconnected, please plug it back and wait a minute" and not refering to the Web bridge

**Comment by mbonani** [comment]
fix in 1550e39203c1d529453c5e7e842c5b28a4660d60
