### ISSUE TITLE
translations

### ISSUE THREAD

**Issue by mbonani** [Mobsya/aseba#526]
- [x]  regenerate files and spread them for translations
-----
- [x] fr
- [x] en
- [x] it
- [ ] de
-----
- [x] pl
- [ ] es
- [ ] el
- [ ] ja
- [ ] ru
- [ ] tr
- [ ] zh

**Comment by mbonani** [comment]
tl seems to be a bug

**Comment by cor3ntin** [comment]
@mbonani supposed to be el

**Comment by mbonani** [comment]
to be redoo for the Wireless configuration

**Comment by cor3ntin** [comment]
@mbonani with the ui change i did yesterday, a few trads need to be updated

**Comment by mbonani** [comment]
blockly is missing for pl, work in progress

**Comment by mbonani** [comment]
blockly is now in pl
I close this issue at it is double of #533
