### ISSUE TITLE
graph in studio should have stop and clear button and export options

### ISSUE THREAD

**Issue by mbonani** [Mobsya/aseba#530]
![image](https://user-images.githubusercontent.com/1000934/57229505-90a78580-7016-11e9-84f0-59c14627fccd.png)

**Comment by mbonani** [comment]
- [ ] add checkbox for time sliding windows 
- [ ] add time input of sliding windows 
- [ ] add pause button
- [ ] add export feature

actual refresh button is on top, re-think where to put all this feature

**Comment by ValentinaTibs** [comment]
What  have to happens when the pause button is pressed?

**Comment by mbonani** [comment]
it has to freeze the graph at the actual view

**Comment by ValentinaTibs** [comment]
and what happens to the X axe when the graph is unpaused?

**Comment by ValentinaTibs** [comment]
[ ] removing the custom dark enable palette that differs from theme to theme
[ ] removing the unity after the 0 from the X-Axis and adding a blank every 3 digits 
[ ] adding the unit measure (milliseconds) in both X-axes and input box
[ ] fix the size of the input box to 6 digit
