### ISSUE TITLE
in studio compilation success should be show and do not let play button be active if code is unvalide

### ISSUE THREAD

**Issue by mbonani** [Mobsya/aseba#531]
like the old: 
![image](https://user-images.githubusercontent.com/1000934/57229756-25aa7e80-7017-11e9-853d-8c76280129f2.png)

shoul not be possible:
![image](https://user-images.githubusercontent.com/1000934/57229994-a5384d80-7017-11e9-8fdd-3f5dbe78c10d.png)
![image](https://user-images.githubusercontent.com/1000934/57230038-be40fe80-7017-11e9-9fdb-db65df0bc620.png)

**Comment by mbonani** [comment]
play button is not more active when not compile code is available

**Comment by cor3ntin** [comment]
@mbonani I don't understand

**Comment by mbonani** [comment]
sorry I just say what it is now implemented and do not reported new bug, it was for me to update this issue with two point
