### ISSUE TITLE
some dialog box are note translated

### ISSUE THREAD

**Issue by mbonani** [Mobsya/aseba#535]
on mac and windows
![image](https://user-images.githubusercontent.com/1000934/57290353-868c9200-70bd-11e9-9314-015a6a7ffee1.png)

only on mac Osx
![image](https://user-images.githubusercontent.com/1000934/57290429-ad4ac880-70bd-11e9-9567-9406dc56a17c.png)

**Comment by cor3ntin** [comment]
Fixed
