### ISSUE TITLE
Dim the "Launch VPL" or "Launch Scratch"... when no robot is selected

### ISSUE THREAD

**Issue by cbarraud** [Mobsya/aseba#539]
![image](https://user-images.githubusercontent.com/4930020/57355575-9fa14b80-716e-11e9-9b6f-ee270f7de64d.png)
I had a feedback from one of our partners suggesting to dim the "Launch" button on the bottom of all the robot selection windows when no robot is selected. This could ease the understanding that you need to either start a simulated robot or click on a physical robot to start the programming interface.

**Comment by cor3ntin** [comment]
I have the same issue with the pairing button in the wireless issue. Can you check with vincent how we can do that ?

**Comment by mbonani** [comment]
done in 18baaf06531c0e59b0ededa10ba12d8df8047e2b
