### ISSUE TITLE
When opening a file in Studio and saving it, it opens the "save as" instead of just saving

### ISSUE THREAD

**Issue by cbarraud** [Mobsya/aseba#545]
When you open a file in Studio (file => open => whatever.aesl), the name of the file doesn't appear on top as shown below:

![image](https://user-images.githubusercontent.com/4930020/57612774-b7fdd580-7575-11e9-9e36-2a88495b8a0f.png)

This leads to the fact that, when you save, it opens the "Save as" pop up instead of just saving over the file you just opened.

**Comment by mbonani** [comment]
yes this is a common behavior that people expext
