### ISSUE TITLE
bwrap: execvp ldconfig: Exec format error

### ISSUE THREAD

**Issue by yauram** [Mobsya/aseba#596]
I have a error when i launch : flatpak run org.mobsya.ThymioSuite
```
bwrap: execvp ldconfig: Exec format error
error: ldconfig failed, exit status 256
```

Any ideas ?

**Comment by cor3ntin** [comment]
Thymio Suite is now available on flathub
https://flathub.org/apps/details/org.mobsya.ThymioSuite

Installing it from there should resolve the issue
