### ISSUE TITLE
in launcher application description is not shown in correct language for macosx - more investigation needed

### ISSUE THREAD

**Issue by mbonani** [Mobsya/aseba#604]
probably missing files?

**Comment by mbonani** [comment]
this append on my macs for testing, OS is in english, description of programs are in english but programs and Suite are in french. On mac OS 10.12.6 Sierra
![Screen Shot 2019-09-05 at 14 21 42](https://user-images.githubusercontent.com/1000934/64341438-a179ff00-cfe8-11e9-9808-2877e9a0b180.png)

**Comment by mbonani** [comment]
I put OS in french all seems ok
![Capture d’écran 2019-09-05 à 14 30 04](https://user-images.githubusercontent.com/1000934/64341920-b6a35d80-cfe9-11e9-8dbb-240a3fa8ffac.png)

**Comment by mbonani** [comment]
I reput english and all seems fine 
![Screen Shot 2019-09-05 at 14 34 13](https://user-images.githubusercontent.com/1000934/64342213-5234ce00-cfea-11e9-83cd-80d249104d8a.png)

**Comment by mbonani** [comment]
mismatch is when you have both language install on your mac 
![Screen Shot 2019-09-05 at 14 37 38](https://user-images.githubusercontent.com/1000934/64342445-cd967f80-cfea-11e9-9d15-c30dd27efc03.png)

**Comment by cor3ntin** [comment]
Seems related to that https://bugreports.qt.io/browse/QTBUG-72491

**Comment by mbonani** [comment]
just to document but for me it is not a priority, whats append, if "primary" language is different of english all program is in that language, if primary language is english description will be english and all programs are in the second language, other are ignore. 
So work around is if you have a language different of english you put it as primary and if you want only english you remove all secondary language and it works. 
![Screen Shot 2019-09-06 at 09 03 33](https://user-images.githubusercontent.com/1000934/64407790-83161100-d085-11e9-9069-5a5d48ceaa83.png)

**Comment by mbonani** [comment]
can we do that from  https://bugreports.qt.io/browse/QTBUG-72491

> The solution has already been written.
> Just create * .proj under the "Resource" folder.
> (It seems that there is no need to put any files in the * .proj folder)
> 
> I have a project for MacAppStore with PySide2.
> I can not use macdeployqt.
> I've combined Py2app with my own script, but the workaround is the same, just create a folder.

**Comment by mbonani** [comment]
fix in 286cbe775b33eba14e7aa8cc08989890ce51ac5e

**Comment by mbonani** [comment]
this strange bug append one time on testing on a fresh installation on Mac OS. 
The computer was in English add second language in french. 
TS was in french and description in English
We switch to french as first language all was in french
We switch back in English all was in English
So there is a strange things how mac manage languages.
