### ISSUE TITLE
Blockly subroutines

### ISSUE THREAD

**Issue by jmwiit** [Mobsya/aseba#619]
Aseba Studio 2.0.0 has a wonderful user interface. Our 9-year-old granddaughter loves it. She has blown through all of the capabilities of VPL, and wants to do more. She is intimidated by the Aseba code, so Blockly seems to be the way for her to go.

A minor stumbling block in Blockly is that one cannot create a subroutine until an event has been created. It doesn't matter whether or not there is any connection between the event handler and the subroutine. It is just that some event handler has to exist before Blockly.

The workaround is obvious, once we had gone through enough trial and error to find it. However, it is counter-intuitive for an elementary school student. It would be nice to get it fixed in some future release.

**Comment by mbonani** [comment]
This is because of the aseba language do not permit subroutine to be called from another place than an event.
