### ISSUE TITLE
simulated robot are not every time shown on OSX

### ISSUE THREAD

**Issue by mbonani** [Mobsya/aseba#637]
sometime when you start a simulator the robot do not appear in the launcher, if you stop the thymio launcher (and let the simulator) when you restart robot are in. 
See on my Sierra 10.12.6

**Comment by cor3ntin** [comment]
I couldm't repro this issue

**Comment by mbonani** [comment]
last test show that in some case it take very long

**Comment by mbonani** [comment]
I see a case with one arena with 16 simulated Thymio and only one appear in the launcher (connectable) now for more than 1 hour. relaunching they appear directly. perhaps a problem with the simulator...

**Comment by mbonani** [comment]
it seems that this bug is not reproductible
