### ISSUE TITLE
on mac osx it is not possible to save and load file in scratch3

### ISSUE THREAD

**Issue by mbonani** [Mobsya/aseba#676]
it is working on Sierra 10.12.6 (but there is the browser)

it is not working on Catalina 10.15

to be teste 10.13 and 10.14

**Comment by mbonani** [comment]
actually it is the same problem for blockly probably a problem with the webtool.

**Comment by cor3ntin** [comment]
Same reason as on iOS - same fix

**Comment by cor3ntin** [comment]
We made scratch open in an external browser, fixing the isue
