### ISSUE TITLE
Scratch 3 : motor speed bug

### ISSUE THREAD

**Issue by MonAssistantNumerique62** [Mobsya/aseba#681]
Hi,
Purpose of the code below is to make Thymio slow down when approaching an object.

When using a motor speed that is a multiple of 5 (10, 15, 20,...) : it works fine.

When using another value (19, 21, 22,...) : the IF condition never occurs, and the loop doesn't end when the distance is under 10.

Tested on Thymio Studio 2 rc3.

![2019_10_19_16_05_30_Thymio_Thymio_1](https://user-images.githubusercontent.com/32057213/67146344-755dc900-f28a-11e9-96d2-8de74cb83ef0.png)

**Comment by mbonani** [comment]
fix in Thymio Studio 2.0.3
