### ISSUE TITLE
fix bonjour version

### ISSUE THREAD

**Issue by mbonani** [Mobsya/aseba#701]

**Comment by cor3ntin** [comment]
Can you please make descriptive issue? I have no idea what this is supposed to be about

**Comment by mbonani** [comment]
It is related to our internal mail with Fanny. 
it's to put the version 3.1 of Bonjour for at least the 64bit version we found in a itune installer. I upload it in the third party. We havn't still found for 32bit because apple do not provide sdk for verions 3.1 but only 3.0
