### ISSUE TITLE
scrolling on macs osx (10.14) seems strange

### ISSUE THREAD

**Issue by mbonani** [Mobsya/aseba#704]
le scroll de la fenêtre de choix des Thymio se comporte très bizarrement: pas de slider latéral tant qu’on ne va pas dessus, si on va dessus il n’apparait pas. Il apparait dès qu’on on scrolle avec le trackpad, mais avec la roulette du mouse le comportement est très bizarre: si tu vas en haut de la fenêtre et tu continues à scroller vers le haut, ensuite tu dois rescroller vers le bas un moment (sans que rien ne bouge) avant d’avoir les éléments qui scrollent. On dirait qu’il intègre le scroll au delà de la fin de page.

**Comment by mbonani** [comment]
it seems ok on osx 10.12
should we let the scrollbar present if it is needet?

**Comment by cor3ntin** [comment]
Should be better
