### ISSUE TITLE
flatpack-Thymio suite shows incorrect icon (default one)

### ISSUE THREAD

**Issue by mbonani** [Mobsya/aseba#712]
tested on Ubuntu 18.04

**Comment by cor3ntin** [comment]
Do you have screens ? What is the correct icon, etc ?

**Comment by mbonani** [comment]
for me it should have the thymio like on other OS

**Comment by cor3ntin** [comment]
It is supposed to have this icon https://github.com/Mobsya/aseba/blob/master/menu/freedesktop/256x256/thymio-launcher.png

**Comment by mbonani** [comment]
![Capture d’écran de 2019-11-15 09-36-00](https://user-images.githubusercontent.com/1000934/68928977-9501e780-078b-11ea-9e05-26362023d77f.png)

**Comment by mbonani** [comment]
strange because when i make show details i have the correct icons:
![Capture d’écran de 2019-11-15 09-39-35](https://user-images.githubusercontent.com/1000934/68929114-ee6a1680-078b-11ea-82e0-94cac48683ac.png)

**Comment by KunjanChauhan** [comment]
Status agreed at 2020 02 17 meeting: 

- [ ] 1. Alessandra will place into PULL REQ by end Tuesday 18th
- [ ] 2. MB will test by end Wednesday 19th 
- [ ] 3. If testing is fine, update policy, finalize and merge into master - Alessandra?

**Comment by mbonani** [comment]
flatpak version is 1.4.3

**Comment by mbonani** [comment]
I update to 1.6.2 same behavior

**Comment by ale-vit** [comment]
The version I tested is 1.6.1

**Comment by mbonani** [comment]
fix in commit 43cfdcd
