### ISSUE TITLE
IOS: add a message "have you launch a Thymio Suite on a computer" when no Thymio are present 

### ISSUE THREAD

**Issue by mbonani** [Mobsya/aseba#720]
Ajouter un message d'erreur "Avez vous lancé Thymio Suite sur un ordinateur relais ? En savoir plus" dans le cas ou aucun robot Thymio n'apparaît dans la liste.

**Comment by abbetch** [comment]
La partie "more information" renverrais au même endroit que le point d'interrogation  sur la première page ?

**Comment by mbonani** [comment]
On devra faire une page, pour l'instant on va mettre une page par default et on pourra changer par la suite
