### ISSUE TITLE
IOS scratch seems less reactive with infinite loop

### ISSUE THREAD

**Issue by mbonani** [Mobsya/aseba#721]
I will put a test case

**Comment by mbonani** [comment]
in fact it is less reactive also on desktop, you can bypass the problem by adding a small wait time in your loop like 0.1sec. In this case it is more reactive. Difficult to say if it is more visisble on tablet, probably a little. 

A small test program you can try is attached 
[test-reaction.zip](https://github.com/Mobsya/aseba/files/3879927/test-reaction.zip)

**Comment by abbetch** [comment]
After de few tests  (ipad / thymio simulator) It seems that the longer the loop is running the less reactive it becomes. I presume that the motors start/stop  are stacking (since they don't seems to take time to be executed). Any other command that take times is fine. (like turn motor X for 1 sec).

**Comment by abbetch** [comment]
I also tested with real devices. Using a cable it seems to work properly. With the wifi we can definitely see the issue (not as bad as in the simulator).
I can also confirm that the issue is also present using thymio suite on the desktop. So it does not seems related to IOS.

**Comment by mbonani** [comment]
yes I agree related to https://github.com/Mobsya/scratch-vm/issues/15
