### ISSUE TITLE
studio play and stop pause step bouton behavior

### ISSUE THREAD

**Issue by mbonani** [Mobsya/aseba#723]
![image](https://user-images.githubusercontent.com/1000934/69352303-01de1b80-0c7d-11ea-81ac-a0fbea1e81e5.png)

It is strange that pause and step button disappear when robot is not in play mode, it make the play and stop button also change place.
It suggest that all button are always shown and put in gray level when no active. 
Also if a correct code is there we should let play button be active even if robot is not stop.

**Comment by cor3ntin** [comment]
> Also if a correct code is there we should let play button be active even if robot is not stop.
What does clicking that button is supposed to do then?

**Comment by mbonani** [comment]
load and run the valide code, you just don't need to stop it before, like in VPL you can run even if robot is not stop before.

**Comment by cor3ntin** [comment]
That is very weird UI wise because it looks like pressing play does nothing

**Comment by mbonani** [comment]
if the code is valide, it should resend it and make the robot start again so play button has always an action, why should the user stop the robot to send the new code?

**Comment by mbonani** [comment]
fix in PR #724
