### ISSUE TITLE
studio drag and drop of array item fails to bring along parent

### ISSUE THREAD

**Issue by mbonani** [Mobsya/aseba#728]
drag and drop should take also the name of the array

![image](https://user-images.githubusercontent.com/1000934/69785559-9df5ae80-11b8-11ea-8413-308324bd530a.png)

**Comment by KunjanChauhan** [comment]
Status agreed at 2020 02 17 meeting: 

- [ ] 1. Davide will check v1.6 Aseba codebase, as it was working previously

**Comment by mbonani** [comment]
fix in cf8edf5089521e7cc82c0dc795c6a285c91ac1af
