### ISSUE TITLE
VPL play button is sometimes active without robot

### ISSUE THREAD

**Issue by mbonani** [Mobsya/aseba#732]
if you unconnected the robot the play button is normally inactive (grayscale) but if you click on undo redo it could become active again also without robot,
<img width="637" alt="Screenshot 2019-11-29 at 15 38 02" src="https://user-images.githubusercontent.com/1000934/69947794-afa7c080-14ee-11ea-95e7-a0963c9ca226.png">

**Comment by KunjanChauhan** [comment]
Status agreed at 2020 02 17 meeting: 

- [ ] 1. Davide will place into pull req
- [ ] 2. Michael to test

**Comment by mbonani** [comment]
fix in 6234c0d5e813a18e04060962e6cf2879a098d68c
