### ISSUE TITLE
[launcher] robot name are  truncated on both ends

### ISSUE THREAD

**Issue by mbonani** [Mobsya/aseba#733]
the mouse over is fine
![image](https://user-images.githubusercontent.com/1000934/69953675-05ce3100-14fa-11ea-9a0f-4d93bbc3328a.png)

**Comment by ValentinaTibs** [comment]
Might be fixed with a newline in case the text does not fit in

**Comment by ValentinaTibs** [comment]
can you please provide monitor configuration?
