### ISSUE TITLE
webgl problem on some win 10 computer

### ISSUE THREAD

**Issue by mbonani** [Mobsya/aseba#737]
Scratch 3 do not launch inside our webtool using chromium (on the BETA 2)  showing a webgl problem:
![Capture d’écran (3)](https://user-images.githubusercontent.com/1000934/71930110-4a08bd00-319b-11ea-8c59-35ca3bcf2d36.png)

users say that webgl is working on is normal Chrome and computer has normally updated drivers also for the graphic card.
![Info systeme](https://user-images.githubusercontent.com/1000934/71930381-d1563080-319b-11ea-96c0-efbcf68062a2.png)

**Comment by mbonani** [comment]
Another user with a 32 bit version:

> J’ai installé Thymio Suite sur un Dell Optiplex360 en dual boot Linux Mint 19 xfce et windows 7 afin que mes élèves puissent programmer Thymio avec Scratch.
> Sous Mint cela fonctionne bien en revanche j’ai le message « Votre navigateur ne supporte pas WebGL » sous W7. Le problème vient donc de ma carte graphique cependant la version Scratch Desktop 3.6 fonctionne sans problème. Serait-il possible d’intégrer cette version dans Thymio Suite ?

**Comment by mbonani** [comment]
we have more and more feedback around this problem, probably updating or configurating the chromium should be sufficient

**Comment by KunjanChauhan** [comment]
Status agreed at 2020 02 17 meeting: 

- [ ] 1. Valentina/Davide to enable Chrome address field so Fanny can test the inbuilt Chrome browser to see if this is the source of the problem
- [ ] 2. in parallel, Valentina to think about other sources of this bug

**Comment by riedo** [comment]
could be this:
https://bugs.chromium.org/p/chromium/issues/detail?id=1036367

**Comment by riedo** [comment]
FYI, some users told me this:

**User 1**
On his computer, he has the webgl error in our embarked browser, but it works fine in his firefox
intel core 2 Duo CPU E7300
Windows 10 64 bits
Firefox Quantum 69.0.1 (64 bits) with settings:
webgl.enable-webgl2 true
webgl.force-enable true

**User 2**
Scratch works in Edge 80.0.361.54, but he gets the webgl error in our embarked browser

**Comment by podak** [comment]
With the first pull request we enabled a text field on the top of the browser with the url of the page. This solution did not work on Windows ( caused the crash of the included browser ), also the look of the text bar did not meet the expectations.
After discussing with Michael, we will propose a fix following a different approach: a checkbox will be added to the launcher, the user will be able to select if use the included browser or the system default one

**Comment by podak** [comment]
After further discussion we decided to move the checkbox on the collapsable right menu of the main page in thymio suite

**Comment by mbonani** [comment]
the checkbox is implemented in 9ab73f2
