### ISSUE TITLE
studio open "recent" file do not work on osx

### ISSUE THREAD

**Issue by mbonani** [Mobsya/aseba#760]
in studio open file normally choosing from finder works, but open files from the "recent" list files do not open the files correctly (code do not appear)  test on osx Sierra 10.12

**Comment by ValentinaTibs** [comment]
@mbonani I've started watching this and from my early observation to me it looks this happens just when the file is not present in the filesystem anymore. 
Can you confirm that the file was still present in the recent file list but not in the filesystem?

**Comment by mbonani** [comment]
I cannot test on the computer I have seen the bug. I make the first test on my actual windows and it seems the behaviour is the same as on the mac when the file is missing from the system.  So it is most probable that the bug is only when the file is missing.

**Comment by ValentinaTibs** [comment]
Confirmed to happen in the following scenario:

1. create a new file 
2. close the editor
3. open the editor
4. select the file from the recent for opening

**Comment by ValentinaTibs** [comment]
Not confirmed on Catalina 
![image](https://user-images.githubusercontent.com/18550002/78254545-6300e000-74f6-11ea-96c9-e7017ace68f0.png)

**Comment by mbonani** [comment]
confirm on 10.14 .4
Is it because the computer are in another languages then EN? so path are translated and it do not correspond on the disk?

**Comment by mbonani** [comment]
fix in latest commit
