### ISSUE TITLE
info do not show correct windows

### ISSUE THREAD

**Issue by mbonani** [Mobsya/aseba#797]
![image](https://user-images.githubusercontent.com/1000934/81692532-d33c4300-945e-11ea-8666-db29a585282a.png)

it should show:
![image](https://user-images.githubusercontent.com/1000934/81692403-a556fe80-945e-11ea-8834-871776cb8e1d.png)

**Comment by podak** [comment]
should have been fixed with the new exported version of vpl3 loaded in ci-data and the PR #799
