### ISSUE TITLE
closing widget button is to much in front when you have zome blocks

### ISSUE THREAD

**Issue by mbonani** [Mobsya/aseba#806]
first thing you do is clicking on it and you close every thing, this closing widget must also warn the user that he is closing the application

![image](https://user-images.githubusercontent.com/1000934/82050664-d16dbc00-96b8-11ea-89e6-374ddcac594a.png)

**Comment by ValentinaTibs** [comment]
Adding a dialog that ask users if they want to Go back to thymio suite 
YES -> 
NO ->

**Comment by mbonani** [comment]
yes-> go back to Thymio Suite (actual behavior)
No-> Stay in VPL or Scratch (close dialog)
