### ISSUE TITLE
Clicking on a music note often modifies the note right of the click target.

### ISSUE THREAD

**Issue by nbornand** [Mobsya/aseba#849]
Using VPL3
Clicking on a music note often modifies the note right of the click target.

**Comment by mbonani** [comment]
Cannot reproduce
Can you give us on wich system/OS you are working?
Kind regards

**Comment by nbornand** [comment]
Using Windows 10 Pro, version 1903 build 18362.1016
Thymio Suite 2.1.0-9cf577cd
Screencast of the bug: https://drive.google.com/file/d/1_E6DOc-CaaWrXSGheVA96JAhjdN0jDsE/view?usp=sharing
The issue seems to only happen for specific window dimensions

**Comment by mbonani** [comment]
OK thank for the video I can reproduce the bug.
It append for me on the include QT browser when the window is full size of the desktop. It also append on Chrome when you play with windows size.

**Comment by nbornand** [comment]
Great thanks. I've also noticed that the same behavior is observed for other blocks as well

**Comment by mbonani** [comment]
fix in latest commit
