### ISSUE TITLE
VPL3 - Cannot inspect code sent to Thymio from Aseba Studio

### ISSUE THREAD

**Issue by nbornand** [Mobsya/aseba#850]
**Setup**
Windows 10 Pro, version 1903 build 18362.1016
Thymio Suite 2.1.0-9cf577cd
**Repro steps**
Create a VPL3 program and load it on a Thymio
Connect to the same robot with "Watch from Aseba Studio"
Observed: The code is empty OR shows the last program sent with VPL 2.*
Expected: Should show the code corresponding to the VPL3 program

**Comment by mbonani** [comment]
This behaviour was not implemented in VPL3, I will see with developers what we do. The generated code is not easy to read and follow as on VPL1.

**Comment by nbornand** [comment]
Alright. Maybe worth checking with Francesco as he was expecting that to work.

**Comment by mbonani** [comment]
this feature was add. Will be available in next release
