### ISSUE TITLE
context menu empty (minor bug )

### ISSUE THREAD

**Issue by rivet-rgb** [Mobsya/aseba#866]
Hello,
Suppose we start Thymio Suite on a computer A connected to a computer B (running Thymio Suite also with a robot) by a network.
On the window of Thymio Suite (computer A) , I right-click on the frame of the robot connnected to computer B.
Nothing appear on the context menu. Is it normal ?
![image](https://user-images.githubusercontent.com/54538162/94987296-a7cd0880-0565-11eb-8c4c-27af8adc2571.png)
Joël Rivet

**Comment by mbonani** [comment]
Hello,
You cannot change name or stop a robot that is not connect on your computer. The idea is that where you connect it is where you control these features (for instance the teacher). If everybody can change or control the robots then it could be a mess in a classroom. 
So yes it is normal. Should we not have context menu if it's empty? perhaps...
Regards
