### ISSUE TITLE
robot not detected on vplv3 but work on legacy vpl

### ISSUE THREAD

**Issue by xens** [Mobsya/aseba#868]
Running aseba 2.1.1 on Ubuntu 20.04, (with proper udev rules as stated in the doc).

The robot is detect on the main menu 

![image](https://user-images.githubusercontent.com/1699826/95649568-43b6c100-0ade-11eb-8b1a-0ae14d2cbb4f.png)

But not anymore inside vplv3

![image](https://user-images.githubusercontent.com/1699826/95649586-5d580880-0ade-11eb-9628-3ad4eb673daa.png)

works fine with the legacy vpl

![image](https://user-images.githubusercontent.com/1699826/95649614-8f696a80-0ade-11eb-8a8b-2bd609041584.png)

Is there a way to obtain more debugging info when launching the aseba suite to give you more input on this issue ?

thanks !

**Comment by mbonani** [comment]
Hello,
Can you please try to update the firmware of the robot? Just click on the circular arrow.
Kind regards

**Comment by xens** [comment]
I did the upgrade and restarted the robot (the circular arrow now disappeared) but vplv3 still marks the robot as "not detected", I tried with the USB cable instead and it's the same behavior, work in both cases (wireless+cable) with vpl but not in both cases with vplv3.

**Comment by mbonani** [comment]
ok is it working with scratch? or blockly?

**Comment by xens** [comment]
yep sorry should have tried before:

* works with Scratch
* works with VPL
* doesn't work with Blocky
* doesn't work with VPLv3

**Comment by mbonani** [comment]
Ok, seems strange that it work with scratch but not with VPL3 or Blockly, all tree are web-based program and connection mechanism is the same. 
You can have more information about debug information launching Thymio Suite by command line:

`flatpak run org.mobsya.ThymioSuite`

 You can also launch before Thymio device manager by hand and have a look. 

`flatpak run --command=thymio-device-manager org.mobsya.ThymioSuite`

**Comment by xens** [comment]
Ok I did a full charge of the robot over the week end (after the battery died) and it's now working with the 4 programs :sweat_smile: so I don't know what fixed it if it's the complete power reset of the robot, or the firmware update or both but now everything is working fine. Closing this issue, thanks for your support @mbonani
