### ISSUE TITLE
Cannot start with simulator

### ISSUE THREAD

**Issue by blackPantherOS** [Mobsya/aseba#878]
I tried use with simulator, cannot start any programming environment.

https://youtu.be/6yCVJimMJdU

**Comment by mbonani** [comment]
I there something that can block zeroconf/avahi on your system?

**Comment by mbonani** [comment]
was it working with previous version?

**Comment by blackPantherOS** [comment]
> I there something that can block zeroconf/avahi on your system?
I don't know about it...
![image](https://user-images.githubusercontent.com/12883566/99067552-33957400-25ab-11eb-8f3f-e2b0590bf4de.png)

> was it working with previous version?
i haven't tried the previous version sorry, but I will check later, if will help you..

**Comment by mbonani** [comment]
Hello,
my avahi looks like that when I have a simulator with 4 robots:
![Capture d’écran de 2020-11-13 12-38-26](https://user-images.githubusercontent.com/1000934/99068813-81ab7700-25ad-11eb-9537-cb0aab670798.png)

So it confirm that the  problem is there, now why? it is difficult to say because I didn't master Linux and your distrib. 
No need to install older one. But you install it using flathub? Or you compile it yourself?

Kind regards

**Comment by blackPantherOS** [comment]
>But you install it using flathub? Or you compile it yourself?

I didn't know this software before, I would like try from flathub repo only. 

The previous picture is not complete, this is good and same as your picture, but missing 'aseba.tcp'
![image](https://user-images.githubusercontent.com/12883566/99071154-dea92c00-25b1-11eb-8db2-628664aa4b6e.png)

**Comment by mbonani** [comment]
The simulator describe itself on aseba.-tcp. "Thymio Device Manager (TDM)" is the one that manage real robots and make an entry point for the software to the local simulator. For sure if aseba.-tcp is missing TDM cannot found them and it is  why there are not shown in Thymio Suite.
I have no idea why the simulator is not describing itself on avahi. It seems that you have several IP address and I am not sure how zeroconf manage that. One difference from simulator and TDM it is that simulator describe itsefl only as local. On my computer I see them only on "lo IPv4"->local, and TDM I see them several time also like you on "eno1 IPv4-6"->local.
So did you have a firewall or something similar that block the simulator, is it a problem between ipv4 -ipv6? difficult to say.
What is you distrib based on?

**Comment by blackPantherOS** [comment]
Solved (i needed some times for the investigate this issue)
So, my distro is same as my name... I build from source a new package (in RPM) and now everything is working fine. Seems the Flatpak package not full compatible with blackPanther avahi, therefore i will rebuild newer version. Thank for your time.
I will adding your suite to blackPanther official repository and our app-warehouse as well

![image](https://user-images.githubusercontent.com/12883566/99183767-8e130980-273e-11eb-8d58-19a762e7cc8f.png)

**Comment by mbonani** [comment]
thank you for investigate
