### ISSUE TITLE
Unable to open Thymio suite in scratch

### ISSUE THREAD

**Issue by chasset** [Mobsya/aseba#919]
Hello,

I am using Thymio suite 2.1.5 on macOS 11.2.3

After selecting on main screen "Scratch" and, on the following screen, "Thymio II" and push the button "Program with Scratch", the software opens a browser window at this URL: file:///private/var/folders/gg/vtdxvv_974l8p10gxg7hqrzr0000gn/T/org.mobsya.ThymioLauncher/tZNAXm.html

This file is created and contains:

```html
<html><head>
  <meta http-equiv="refresh" content="0;URL='file:///Applications/ThymioSuite.app/Contents/Resources/scratch/index.html?device=%7B6007deb6-3a58-4b50-bca1-2b944d0d90de%7D&ws=ws://127.0.0.1:8597" />
</head></html>
```

But, after a few seconds, this file is deleted.

It doesn’t work either with vpl3 or blockly.

Is there a dependency to satisfy?

Best regards,

Pierre-Olivier

**Comment by mbonani** [comment]
Hello,
Could you perhaps try with another default system browser like Chrome?
Kind regards

**Comment by mbonani** [comment]
Anyway the URL Inside the file is the correct one. I think this it is a protection mechanism of Apple/Safari

**Comment by chasset** [comment]
It works! Many thanks
